name: Build and Test

on:
  pull_request:
  push:
    branches:
      - github_workflows
    tags:
      - '*'

jobs:
  test_run_docker:
    runs-on: ubuntu-latest
    steps:
      - run: gradle --version
      - uses: docker://jhvjkcyyfdxghjk/isax-tools-integration-env:latest
      - run: gradle --version
  build:
    runs-on: ubuntu-latest
    container:
      image: jhvjkcyyfdxghjk/isax-tools-integration-env:latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set Gradle home
        run: |
          echo "GRADLE_USER_HOME=$(pwd)/.gradle" >> $GITHUB_ENV

      - name: Restore Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            frontend
            app/build
            .gradle
          key: build-${{ github.ref_name }}

      - name: Build
        run: gradle --build-cache assemble

      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: |
            frontend
            app/build
            .gradle
          key: build-${{ github.ref_name }}

  test:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: jhvjkcyyfdxghjk/isax-tools-integration-env:latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set Gradle home
        run: |
          echo "GRADLE_USER_HOME=$(pwd)/.gradle" >> $GITHUB_ENV

      - name: Restore Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            frontend
            app/build
            .gradle
          key: build-${{ github.ref_name }}

      - name: Test
        run: gradle check

  release:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    container:
      image: jhvjkcyyfdxghjk/isax-tools-integration-env:latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Restore Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            frontend
            app/build
            .gradle
          key: build-${{ github.ref_name }}

      - name: Prepare release artifact
        run: |
          mkdir treenail
          cd treenail
          tar xf ../app/build/distributions/app.tar --strip-components=1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: treenail
          path: treenail/**
