name: Build and Test

on:
  push:
    branches:
      - github_workflows
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  before_script:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Gradle
        run:
          docker run -v ./treenail:/treenail -v ~/.ssh:/var/empty/.ssh -it docker.io/jhvjkcyyfdxghjk/isax-tools-integration-env:latest
          cd /treenail
          GRADLE_USER_HOME="$(pwd)/.gradle"
          export GRADLE_USER_HOME
  build:
    runs-on: ubuntu-latest
    needs: before_script
    steps:
      - name: Build treenail
        run: gradle --bulid-cache assemble
    # TODO: cache
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run treenail tests
        run: gradle check
    # TODO: cache
      
