name: Build and Test

on:
  push:
    branches:
      - github_workflows
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  one_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set gradle user home
        run: GRADLE_USER_HOME="$(pwd)/.gradle"
      - name: Export gradle user home
        run: export GRADLE_USER_HOME
      - name: Get Treenail
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Build treenail
        run: gradle --build-cache assemble
      - name: Run treenail tests
        run: gradle check
    # TODO: cache
      
