name: Build and Test

on:
  push:
    branches:
      - github_workflows
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  before_script:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Gradle
        run:
          GRADLE_USER_HOME="$(pwd)/.gradle"
          export GRADLE_USER_HOME
  get_treenail:
    runs-on: ubuntu-latest
    steps:
      - name: Get Treenail
        uses: actions/checkout@v3
  build:
    runs-on: ubuntu-latest
    needs: [before_script, get_treenail]
    steps:
      - name: Build treenail
        run: gradle --build-cache assemble
    # TODO: cache
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run treenail tests
        run: gradle check
    # TODO: cache
      
